### ISSUE TITLE
Tangut still appears in CLICS!

### ISSUE THREAD

**Issue by LinguList** [lexibank/suntb#2]
This needs to be deleted from the list of languages, as Tangut has only "--" in STEDT, and surfaces as "--" in CLICS or as nothing, because they have characters in the original source that were not digitized by the STEDT project. Currently, all Tangut entries are still transferred to CLDF output, although they are meaningless.

**Comment by tresoldi** [comment]
I remember this problem, either I forgot to fix it back in December or the fix is not working. I'll check today.

**Comment by tresoldi** [comment]
Commit 61ea0b5 fixes this.
