### ISSUE TITLE
bika1249 wrong glottocode

### ISSUE THREAD

**Issue by LinguList** [lexibank/suntb#3]
This needs to be changed, as this glottocode does not work.

**Comment by Wu-Urbanek** [comment]
found it, should I change the glottolog code now? 
It is "dazh1234"

**Comment by LinguList** [comment]
what are language name etc in SUNTB and glottolog?

**Comment by Wu-Urbanek** [comment]
It's Hani (Dazhai)

**Comment by Wu-Urbanek** [comment]
update the Glottolog code in etc/languages.csv
